### ISSUE TITLE
Class 'com\wowza\entities\application\AdvancedSettings' not found

### ISSUE THREAD

**Issue by YingChen-dci** [WowzaMediaSystems/wse-rest-library-php#14]
Hi,
I am trying to get advanced setting by using PHP. However when I tried to run application.php, the following Error shows up, and indicate that on line 40 of application.php.

-- PHP Fatal error:  Uncaught Error: Class 'com\wowza\entities\application\AdvancedSettings' not found

I looked into entities\application\AdvancedSetting and helpers, couldn't find any should be suspected.

I ran application.php without make any change first, above error shows. Then I comment out advanced setting lines, it works well

Do I miss anything?
Does anyone have any ideas on this issue?

**Comment by rogerlittin** [comment]
Hi,

Please retest. We've just finished pulling in a major rewrite.

-Roger.

**Comment by YingChen-dci** [comment]
Hello,
GREAT NEWS!! 
Thanks a lot! I will retest it!! 
I was wondering does anyone notice this post...

Thanks again,
-Ying

**Comment by IWriteThings** [comment]
Closing this issue. Please reopen or make a new ticket if you continue to have issue with the latest code release.
