### ISSUE TITLE
400 malformed syntax error

### ISSUE THREAD

**Issue by YingChen-dci** [WowzaMediaSystems/wse-rest-library-php#17]
Hello there,

I tried to create live stream's recording, but the following error keep showing up.

- POST method
code : 400
message : The request could not be understood by the server due to malformed syntax

I also tried to create user/publisher, same error returned. 

I used "curl" command with same URL(POST method), in case I put wrong URL. However it works well(returned success:true). PUT method shows no match URI error(I tried split recording too).

By the way, it was doing great 2weeks ago, 400 shows just so sudden. I also tried version4.6 and 4.5 wowza servers, same error. 

It would be great if I could hear any from you.

**Comment by IWriteThings** [comment]
Post the exact curl request you are using or code that is initiating the request. The issue you are having appears to be in your syntax and not an issue with the wowza code.

**Comment by YingChen-dci** [comment]
At the first place, I thought that might be my syntax problem, however I just simply tried to create live stream source(using publishers.php that could be found in the wse-rest-library-php project Code), and followed the below document said.
https://www.wowza.com/docs/live-sources-php-query-examples-for-the-wowza-streaming-engine-rest-api

Here is the code I used, just changed the name and passwer.
-----
<?php
require_once("../include/config.php");

$sf = new com\wowza\Publisher("testUser00");
$response = $sf->create("mF5TdZ");
var_dump($response);
-----

The following is return.
-----
JSON REQUEST to http://HOSTNAME:8087/v2/servers/_defaultServer_/publishers with verb POST: {"restURI":"http:\/\/HOSTNAME:8087\/v2\/servers\/_defaultServer_\/publishers","name":"testUser00","password":"mF5TdZ"}
RETURN: {"message":"The request could not be understood by the server due to malformed syntax","code":"400","success":false,"wowzaServer":"4.7.0.02"}
object(stdClass)#4 (4) {
  ["message"]=>
  string(73) "The request could not be understood by the server due to malformed syntax"
  ["code"]=>
  string(3) "400"
  ["success"]=>
  bool(false)
  ["wowzaServer"]=>
  string(8) "4.7.0.02"
}
-----

**Comment by YingChen-dci** [comment]
At the first place I thought it might be my syntax error. However I just simply tried to create publisher and followed the below document. The below code I used to do the testing, also can be found from wse-rest-library-php project's code(publisher.php).

`require_once("../include/config.php");

$sf = new com\wowza\Publisher("testUser00");
$response = $sf->create("mF5TdZ");
var_dump($response);`

Here is the return value.
`JSON REQUEST to http://HOSTNAME:8087/v2/servers/_defaultServer_/publishers with verb POST: {"restURI":"http:\/\/HOSTNAME:8087\/v2\/servers\/_defaultServer_\/publishers","name":"testUser00","password":"mF5TdZ"}
RETURN: {"message":"The request could not be understood by the server due to malformed syntax","code":"400","success":false,"wowzaServer":"4.7.0.02"}
object(stdClass)#4 (4) {
  ["message"]=>
  string(73) "The request could not be understood by the server due to malformed syntax"
  ["code"]=>
  string(3) "400"
  ["success"]=>
  bool(false)
  ["wowzaServer"]=>
  string(8) "4.7.0.02"
}`

**Comment by IWriteThings** [comment]
You are using the old rest library with this code. Can you update to the latest?

**Comment by IWriteThings** [comment]
Since this ticket references old code, I am going to close it. Please try the new code found in the master branch. If you update your code to use the new code and still have issues, please contact me in the ticket system and we will look into helping you out. Thanks a bunch!
