### ISSUE TITLE
Fatal Error - first test

### ISSUE THREAD

**Issue by falcaosurfline-zz** [WowzaMediaSystems/wse-rest-library-php#22]
Just added the extra lines in include/constants.php to file for configuration.

But I can´t make it work...

create this test file for debug and it doesn´t work:

echo 'Curl: ', function_exists('curl_version') ? 'Enabled' : 'Disabled';
require_once("../include/config.php");
$sf = new com\wowza\User();
$response = $sf->getAll();

Fatal error: Uncaught Error: Class 'com\wowza\User' not found in /var/www/html/wse-rest-library-php-master/tests/me.php:8 Stack trace: #0

**Comment by IWriteThings** [comment]
Documentation has changed. To answer you -


```
<?php
//index.php

require_once(__DIR__.'/../vendor/autoload.php');

// This is for a framework if you use one.
//$framework = new Project\Framework();
//$framework->registerDebugHandlers();
//$framework->processHttpSapiRequest();

require_once("../config.php"); // make sure this exists and is similar to the below - move it where it needs to be
```
```
<?php
// config.php
define("WOWZA_HOST","http://111.111.123.123:8087/v2");
define("WOWZA_SERVER_INSTANCE", "_defaultServer_");
define("WOWZA_VHOST_INSTANCE", "_defaultVHost_");
define("WOWZA_USERNAME", "my_secret_username");
define("WOWZA_PASSWORD", "my_super_cool_password");

// It is simple to create a setup object for transporting our settings
$setup = new Com\Wowza\Entities\Application\Helpers\Settings();
$setup->setHost(WOWZA_HOST);
$setup->setUsername(WOWZA_USERNAME);
$setup->setPassword(WOWZA_PASSWORD);

// Connect to the server or deal with statistics NOTICE THE CAPS IN COM AND WOWZA
$server = new Com\Wowza\Server($setup);
$sf = new Com\Wowza\Statistics($setup);
$response = $sf->getServerStatistics($server);
var_dump($response);
```

Please use this for now as your example to get you started while I work on documentation and cleaning stuff up. Also feel free to contribute as you find issues or fix items.

**Comment by IWriteThings** [comment]
I have made updates to both the readme as well as made changes in code. Please reference the documentation change and if you continue to have issues with the new code and new documentation, please let us know. Closing this ticket as it references old instructions.
