### ISSUE TITLE
Register with Packagist

### ISSUE THREAD

**Issue by IWriteThings** [WowzaMediaSystems/wse-rest-library-php#24]
https://packagist.org/

Packagist is the repository that simplifies how composer is used and deployed. Packagist aggregates public packages made available through composer.

Would someone at Wowza like to register the wse-rest-library-php at packagist and make it available there? The composer.json is correct and all the heavy lifting is done. Someone just needs to register the library there and submit it. Packagist will crawl the library on a regular interval and keep it up to date as appropriate.

Please contact me with questions here or let's discuss elsewhere if necessary.

Thanks!

**Comment by rogerlittin** [comment]
Hi,

Can you log into the Wowza portal and open a support ticket so this can be routed to the right person to handle it.

https://store.wowza.com/portal/account

Thanks,

Roger.

**Comment by IWriteThings** [comment]
Message sent as per your request.

**Comment by IWriteThings** [comment]
Update:

Packagist will require a point release system. Improvements inbound for getting wse ready for upload to packagist.

**Comment by IWriteThings** [comment]
https://packagist.org/packages/wowza/wse-rest-library-php

We are now registered on packagist. Hooray!
