### ISSUE TITLE
Create a Development Branch

### ISSUE THREAD

**Issue by IWriteThings** [WowzaMediaSystems/wse-rest-library-php#27]
Roger,

Please create a branch called 'dev' or 'development'. It should be a copy of the current state of master. This will be an unstable branch used to store bleeding edge updates to the wse-rest-library. It should never be deleted upon merge with master. Jim and I spoke and there is an interest in moving to a point release system with a master,development,feature relationship.

Thanks!

**Comment by JAAulde** [comment]
I've created the branch, `develop`. Would you agree that, going forward with our git worklfow for releasing versions, we should make `develop` the default branch?

**Comment by IWriteThings** [comment]
https://www.atlassian.com/git/tutorials/comparing-workflows

Develop will be where we branch off of. However, early on, I am going to be making a lot of fixes and just piling them in so we can get this thing off the ground. Moving forward, master should just be releases. Thanks a bunch for making the branch!
