### ISSUE TITLE
Is it possible to create a custom advanced application setting?

### ISSUE THREAD

**Issue by magkopian** [WowzaMediaSystems/wse-rest-library-php#34]
Is there any way during the creation of an application, to add a custom advanced setting? I’m using [ModuleSecureURLParams](https://www.wowza.com/docs/how-to-secure-publishing-from-an-rtmp-encoder-that-does-not-support-authentication-modulesecureurlparams), which requires me to set a custom advanced application setting, with the name of `secureurlparams.publish` and the value of `<password>.doPublish`.

Including the module to the application is pretty straight forward. All I did was the following,

```php
$modules = new \Com\Wowza\Entities\Application\Modules();
$modules->moduleList[] = $modules->getModuleItem("ModuleSecureURLParams", "ModuleSecureURLParams", "com.wowza.wms.security.ModuleSecureURLParams");
```

But when it come to creating the custom advanced setting I’m pretty much stuck. So, far I did the following,

```php
$advancedItemSecureUrlParams = new \Com\Wowza\Entities\Application\Helpers\AdvancedSettingItem();
$advancedItemSecureUrlParams->enabled = true;
$advancedItemSecureUrlParams->canRemove = false;
$advancedItemSecureUrlParams->name = 'secureurlparams.publish';
$advancedItemSecureUrlParams->value = '<password>.doPublish';
$advancedItemSecureUrlParams->defaultValue = null;
$advancedItemSecureUrlParams->type = 'String';
$advancedItemSecureUrlParams->sectionName = 'Application';
$advancedItemSecureUrlParams->section = '/Root/Application';
$advancedItemSecureUrlParams->documented = false;

$AdvancedSettings = new \Com\Wowza\Entities\Application\AdvancedSettings();
$AdvancedSettings->advancedSettings[] = $advancedItemSecureUrlParams;
```

But from there, I have no idea what I should do next. The `create` method of the `Application` class, does accept an object of the `Modules` class, but there is no argument that can be passed for an object of the `AdvancedSettings` class.

By the way, after a bit of digging in the commit history. I did found this commit a54150d4d84453f18fd232e3cca5e0d6cba40f6b, which introduced a `createAdvanced` method to the `Application` class. But later, on c81b479f17935e3042f1719eb0209357674fc32f this method was removed from the [tests/application.php](https://github.com/WowzaMediaSystems/wse-rest-library-php/blob/master/tests/application.php) example.

**Comment by magkopian** [comment]
I ended up forking the repository and adding support for updating the advanced settings of an application myself. I also added the ability to get the advanced settings, because it didn't exist as well.

For anyone interested you can find my changes [here](https://github.com/WowzaMediaSystems/wse-rest-library-php/compare/master...magkopian:master). If you think my code is good enough I can submit a pull request, otherwise please point me to what you think it needs to be fixed.

Finally, here is an example for using this feature,

```PHP
// First we define the advanced setting item
$advancedItemSecureUrlParams = new \Com\Wowza\Entities\Application\Helpers\AdvancedSettingItem();
$advancedItemSecureUrlParams->enabled = true;
$advancedItemSecureUrlParams->canRemove = false;
$advancedItemSecureUrlParams->name = 'secureurlparams.publish';
$advancedItemSecureUrlParams->value = '<password>.doPublish';
$advancedItemSecureUrlParams->defaultValue = null;
$advancedItemSecureUrlParams->type = 'String';
$advancedItemSecureUrlParams->sectionName = 'Application';
$advancedItemSecureUrlParams->section = '/Root/Application';
$advancedItemSecureUrlParams->documented = false;

// Then we get the advanced setting and add it to the rest of the advanced settings
$advanced = $application->getAdvanced();
$advancedSettings = new \Com\Wowza\Entities\Application\AdvancedSettings();
$advancedSettings->advancedSettings = $advanced->advancedSettings;
$advancedSettings->advancedSettings[] = $advancedItemSecureUrlParams;

// We also add the modules so they want get wipe from the update of the advanced section
$modules = new Modules();
$modules->moduleList = $advanced->modules;

// Finally, we update the advanced section of the application
$response = $application->updateAdvanced($advancedSettings, $modules);
```

**Comment by IWriteThings** [comment]
Please pull the latest and create a merge request for this.

Thanks!
Aaron

**Comment by IWriteThings** [comment]
This has been merged and is now available in main.

Thanks for this!
