### ISSUE TITLE
how to write rest api? , i got fatal error ? 

### ISSUE THREAD

**Issue by thirunasky7** [WowzaMediaSystems/wse-rest-library-php#43]
Fatal error: Class 'Com\Wowza\Wowza' not found in /opt/lampp/htdocs/wse-rest-library-php-master/src/Application.php on line 11

**Comment by IWriteThings** [comment]
Please post your code.

**Comment by thirunasky7** [comment]
i just run this gitup file in my local

**Comment by IWriteThings** [comment]
Sounds like you are not using the composer install. You need to include all the files in the src directory, which is a mess and really isn't supported. I would need you to post your code to help trouble shoot it. Closing this ticket.
