### ISSUE TITLE
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS)

### ISSUE THREAD

**Issue by jjtainio** [WowzaMediaSystems/wse-rest-library-php#49]
Hi

I'm testing the wse-rest-library-php with the Example configuration given in documentation (index.php, config.php). 

When testing the page, I get the following error to Apache error log:

PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/html/nopolacontrol/vendor/wowza/wse-rest-library-php/src/Server.php on line 25
 
Is there something, I'm doing wrong? A quick peek to the Server.php -file did not reveal anything obvious.

**Comment by IWriteThings** [comment]
Please post your config / the method you are using to call the Server file. It would appear you have an improperly closed statement or a variable that is missing a $ symbol.

**Comment by jjtainio** [comment]
I'm using the example from the Configuration Example, just changed the config.php name to cfg.php and used different path for it.

Centos 7.4.1708, apache and php version is:

PHP 5.4.16 (cli) (built: Mar  7 2018 13:34:47) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

-- index.php
```
<?php
//index.php

require_once(__DIR__.'/../vendor/autoload.php');

// This is for a framework if you use one.
//$framework = new Project\Framework();
//$framework->registerDebugHandlers();
//$framework->processHttpSapiRequest();

require_once("../config/cfg.php"); // make sure this exists and is similar to the below - move it where it needs to be

```


-- cfg.php


```
<?php
// cfg.php
define("WOWZA_HOST","http://localhost:8087/v2");
define("WOWZA_SERVER_INSTANCE", "_defaultServer_");
define("WOWZA_VHOST_INSTANCE", "_defaultVHost_");
define("WOWZA_USERNAME", "myser");
define("WOWZA_PASSWORD", "mypass");

// It is simple to create a setup object for transporting our settings
$setup = new Com\Wowza\Entities\Application\Helpers\Settings();
$setup->setHost(WOWZA_HOST);
$setup->setUsername(WOWZA_USERNAME);
$setup->setPassword(WOWZA_PASSWORD);

// Connect to the server or deal with statistics NOTICE THE CAPS IN COM AND WOWZA
$server = new Com\Wowza\Server($setup);
$sf = new Com\Wowza\Statistics($setup);
$response = $sf->getServerStatistics($server);
var_dump($response);

```
---

**Comment by IWriteThings** [comment]
Are you on PHP 7 or 5?

**Comment by jjtainio** [comment]
PHP 5.4.16

**Comment by jjtainio** [comment]
Any news on this?

**Comment by haridarshan** [comment]
@jjtainio 

That because `self::class` is not supported in 5.4.16, You need to upgrade PHP version from 5.4 to 5.5 or later

**Comment by jjtainio** [comment]
Ok thanks for the info, upgraded to php 7.0, no error on the apache logs, but the only response, I get with the api example above, is "NULL"

**Comment by jjtainio** [comment]
The problem was, I was using "localhost" on WOWZA_HOST, which defaulted to ipv6 and my Wowza server is not using IPV6. Used "127.0.0.1" instead.

**Comment by jjtainio** [comment]
Also on Centos, httpd can't connect anywhere as default, use "setsebool -P httpd_can_network_connect on" if you want get this to work. Hope this saves someone half a day of searching. (The library returns "NULL" as response to this.)

**Comment by IWriteThings** [comment]
The PHP version used was too out of date. Closing this issue.

**Comment by ujjwalsrivastava** [comment]
Just put semiclon after
defined('BASEPATH') OR exit('No direct script access allowed') this before the class.
and your error simplified.

**Comment by adyatilmi** [comment]
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /home/thumartc/public_html/index.php on line 50
