### ISSUE TITLE
Class TranscoderConfig missing parameter in SetURI

### ISSUE THREAD

**Issue by cbevans** [WowzaMediaSystems/wse-rest-library-php#5]
The setURI function in transcoderconfig (line 17 in class.transcoderconfig.php) is not compatible with the version in class.entity.php (line 35) that it inherits from because the parameter is missing from the function declaration.

Corrected version:
```
        public function setURI($baseURI){
                $this->restURI = $baseURI."/transcoder";
        }
```

**Comment by myoung1620** [comment]
Should be fixed in the latest commit, thanks.
