### ISSUE TITLE
wowza

### ISSUE THREAD

**Issue by lakhasajid081** [WowzaMediaSystems/wse-rest-library-php#59]
with this can i create a new wowza application from my website

**Comment by haridarshan** [comment]
@lakhasajid081 

Yes you can create wowza application using Wowza Rest Api Library

What do you want to develop?

**Comment by lakhasajid081** [comment]
i want to create an app in wowza through my web i mean i need an option with it i need to create an application of wowza in wowza server.

**Comment by lakhasajid081** [comment]
please see this error and tell me the solution of it please
https://imgur.com/QNzMb9i

**Comment by haridarshan** [comment]
Can you please share the application.php. From the error it seems, wowza rest library is not autoloaded

**Comment by lakhasajid087** [comment]
sir can you please explain me step by step guide or share with me if you have any videos regarding this project that how can i make a website with wowza streaming engine api i just want to create wowza application from my site

**Comment by lakhasajid081** [comment]
sir can you please explain me step by step guide or share with me if you have any videos regarding this project that how can i make a website with wowza streaming engine api i just want to create wowza application from my site

**Comment by Wowza-Rose** [comment]
The Wowza website has a lot of documentation on the REST API and here is a good starting point for you as far as docs:
(https://www.wowza.com/docs/wowza-streaming-engine-rest-api)

We have several video tutorials as well here:
https://www.youtube.com/channel/UCLBd5aN6IF2qzos2Wn5Rtvw

Feel free to join the Wowza forums community and chat with developers around the world:
https://www.wowza.com/community/index.html

**Comment by akeller** [comment]
Closing as stale.
