### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by TheWiseNoob** [WowzaMediaSystems/wse-rest-library-php#61]
The last update was over a year ago and the latest issue before this one clearly does not need to be open. Can I rely on this working if I use it in production?

**Comment by akeller** [comment]
Appreciate the concern here. I would be asking the same thing if I were looking to use this. 

We have folks using the REST API today, some use this wrapper or have built something on their own. If you are concerned, I would use the API directly. 

That said, I'm looking at cleaning up this repo as I've done some of the others. 

Question for you - if we were to open source this PHP wrapper, would you be willing to help support it with contributions?

**Comment by TheWiseNoob** [comment]
I could try. I don't know if I could use the API directly. Never have and I'm JUST learning this API wrapper. I was hoping to use this in a Laravel project for a video streaming site I made and am maintaining. Is the API this is a wrapper for just require using cURL like [here](https://www.wowza.com/docs/how-to-query-wowza-rest-api)?

**Comment by haridarshan** [comment]
This wrapper is still in development stage and to release it's first version, It's require support by which we can make it possible. 

I've a pull request pending from May 2018 and unfortunately none of the contributors have write access to this repo. So, I would suggest, if we can fork it and merge all changes to that new repo and maintain it or @IWriteThings  can provide write access to some of active contributors

**Comment by akeller** [comment]
Let me review the pull requests and see what I can do.

**Comment by akeller** [comment]
Good news everyone! I'm working on updates to the README as well as adding supporting documents to make this an open source project moving forward. I will triage any new PRs and issues, identify anything that might be a feature request to the API that the internal engineering team would need to handle. Community members will maintain this moving forward.
