### ISSUE TITLE
Add "Destination Application Name" in Stream Target Create 

### ISSUE THREAD

**Issue by paulm17** [WowzaMediaSystems/wse-rest-library-php#7]
I wanted to stream to youtube live, so I needed this capability.

Line 26:

    - public function create($sourceStreamName=null, $entryName=null, $profile=null, $host=null, $userName=null, $password=null, $streamName=null){

    + public function create($sourceStreamName=null, $entryName=null, $profile=null, $host=null, $application=null, $userName=null, $password=null, $streamName=null){

Line 33:

    + $this->application = (!is_null($application))?$application:$this->application;

**Comment by rogerlittin** [comment]
Hi,

This has been done now.
