### ISSUE TITLE
installation via composer does not work

### ISSUE THREAD

**Issue by taalralgo** [WowzaMediaSystems/wse-rest-library-php#70]
Here is error messsage "Could not find a version of package wowza/wse-rest-library-php matching your minimum-stability (stable). Require it with an explicit version constraint allowing   
   its desired stability."

**Comment by taalralgo** [comment]
There is no license information available for the latest version (dev-main) of this package.

**Comment by haridarshan** [comment]
@taalralgo 
If you have defined [minimum-stability](https://getcomposer.org/doc/04-schema.md#minimum-stability) in your composer.json, for sure you'll have warning using.

Can you please share composer.json

**Comment by jklee210104** [comment]
composer require "wowza/wse-rest-library-php:dev-master"

                                                                                                                        
  [InvalidArgumentException]                                                                                            
  Could not find package wowza/wse-rest-library-php in a version matching "dev-master" and a stability matching "dev".  

We're developing with php 7.4

**Comment by haridarshan** [comment]
@taalralgo @jklee210104 
use `composer require "wowza/wse-rest-library-php:dev-main"` to install the package

**Comment by jklee210104** [comment]
It works. thx for replying
